---
- include: debian.yml
  when: ansible_os_family == "Debian"

- name: ensure pools are defined
  sudo: yes
  template: src=pool.conf.j2 dest=/etc/php5/fpm/pool.d/{{ item.name }}.conf validate="php5-fpm -y %s -t"
  with_items: php5_fpm_pools
  notify:
    - reload php5-fpm
  tags:
    - php5-fpm
